
  import 'package:hsequize/models/quize_level.dart';

import 'enums.dart';
import 'models/quiz_category.dart';
import 'models/quize.dart';
const levels = [
  QuizLevel(number: 0, pointsGained: 10, pointsLost: 10),
  QuizLevel(number: 1, pointsGained: 20, pointsLost: 20),
  QuizLevel(number: 2, pointsGained: 30, pointsLost: 30),
  QuizLevel(number: 3, pointsGained: 40, pointsLost: 40),
  QuizLevel(number: 4, pointsGained: 50, pointsLost: 50),
];
var quizeData =  [
  QuizCategory(
    name: 'Hazard Identification',
    description: 'This quiz is About hazard identification',
    isUnlocked: false,
    //iconImage: 'assets/images/animated movies.jpg',
    quizzes: [
      Quiz(question: 'What is a hazard??',
          options: const ['Anything that can cause harm', 'A type of personal protective equipment (PPE)', 'scheduled break time', 'A routine task'],
          correctIndex: 0,
          hint: '',
          questionType: QuizQuestionType.text,
          level: levels[0]),
      Quiz(question: 'Which of the following is an example of a physical hazard??',
          options: const ['Noise', 'Chemical spill', 'Poor lighting', 'Heavy lifting'],
          correctIndex: 0,
          hint: '',
          questionType: QuizQuestionType.text,
          level: levels[0]),
      Quiz(question: 'What should you do if you identify a potential hazard at work?',
                options: const ['Ignore it', 'Report it to a supervisor', 'Continue working', 'Tell a coworker'],
                correctIndex: 0,
                hint: '',
                questionType: QuizQuestionType.text,
                level: levels[0]),
      Quiz(question: 'How can ergonomic hazards be reduced??',
                options: const ['By ignoring them', 'Using proper posture and lifting techniques', 'By skipping breaks', 'By overloading workstations'],
                correctIndex: 1,
                hint: '',
                questionType: QuizQuestionType.text,
                level:levels[0]),
      Quiz(question: 'Which of these is an example of a chemical hazard??',
                options: const ['Slippery floor', 'Loud machinery', 'Toxic fumes', 'Heavy boxes'],
                correctIndex: 2,
                hint: '',
                questionType: QuizQuestionType.text,
                level:levels[0]),
      Quiz(question: 'What is the first step in hazard identification??',
                options: const ['Taking a coffee break', 'Conducting a risk assessment', 'Reporting to a colleague', 'Documenting safety protocols'],
                correctIndex: 2,
                hint: '',
                questionType: QuizQuestionType.text,
                level: levels[0]),
      Quiz(question: 'Which of the following is a biological hazard??',
                options: const ['Inadequate lighting', 'Broken equipment', 'Bacteria', 'Overcrowded workspace'],
                correctIndex: 2,
                hint: '',
                questionType: QuizQuestionType.text,
                level: levels[0]),
      Quiz(question: 'How often should hazard assessments be conducted??',
                options: ['Once a year', 'Whenever it\'s convenient', 'Regularly, as part of routine safety checks', 'Only after an incident occurs'],
                correctIndex: 2,
                hint: '',
                questionType: QuizQuestionType.text,
                level: levels[0]),


            Quiz(question: 'What type of hazard is associated with exposure to loud noise in the workplace?',
                options: ['Biological Hazard', 'Chemical Hazard', 'Physical Hazard', 'Ergonomic Hazard'],
                correctIndex: 2,
                hint: '',
                questionType: QuizQuestionType.text,
                level: levels[1]),
            Quiz(question: 'Which of the following is a common hazard in a chemical laboratory?',
                options: ['Repetitive Motion', 'Slips, Trips, and Falls', 'Chemical Spills', 'Inadequate Lighting'],
                correctIndex: 2,
                hint: '',
                questionType: QuizQuestionType.text,
                level: levels[1]),
            Quiz(question: 'What type of hazard is represented by repetitive tasks that strain the muscles and joints?',
                options: ['Electrical Hazard', 'Ergonomic Hazard', 'Biological Hazard', 'Physical Hazard'],
                correctIndex: 1,
                hint: '',
                questionType: QuizQuestionType.text,
                level: levels[1]),
            Quiz(question: 'Which of the following hazards is associated with exposure to infectious diseases?',
                options: ['Physical Hazard', 'Chemical Hazard', 'Biological Hazard', 'Ergonomic Hazard'],
                correctIndex: 2,
                hint: '',
                questionType: QuizQuestionType.text,
                level: levels[1]),
            Quiz(question: 'What type of hazard is posed by inadequate ventilation in a confined space?',
                options: ['Chemical Hazard', 'Physical Hazard', 'Ergonomic Hazard', 'Biological Hazard'],
                correctIndex: 0,
                hint: '',
                questionType: QuizQuestionType.text,
                level: levels[1]),
    ],
  ),
  QuizCategory(
    name: 'Risk Assessment',
    description: 'This quiz is About risk assessment',
    //iconImage: 'assets/images/animated movies.jpg',
    quizzes: [
      Quiz(question: 'What is the first step in conducting a risk assessment?',
          options: ['Implementing control measures', 'Identifying hazards', 'Evaluating risks', 'Reviewing the assessment'],
          correctIndex: 1,
          hint: '',
          questionType: QuizQuestionType.text,
          level: levels[0]),
    Quiz(question: 'Which of the following is an example of a physical control measure?',
          options: ['Training employees on safety procedures', 'Installing guardrails', 'Conducting safety drills', 'Creating safety policies'],
          correctIndex: 1,
          hint: '',
          questionType: QuizQuestionType.text,
          level: levels[0]),
    Quiz(question: 'What is a common tool used to evaluate the severity of a risk?',
          options: ['Risk Matrix', 'SWOT Analysis', 'Fishbone Diagram', 'Pareto Chart'],
          correctIndex: 0,
          hint: '',
          questionType: QuizQuestionType.text,
          level: levels[0]),
    Quiz(question: 'Which of the following factors is NOT typically considered in a risk assessment?',
          options: ['Likelihood of occurrence', 'Severity of impact', 'Financial cost of control measures', 'Historical data of past incidents'],
          correctIndex: 2,
          hint: '',
          questionType: QuizQuestionType.text,
          level: levels[0]),
    Quiz(question: 'What is the main purpose of risk assessment?',
          options: ['To eliminate all risks', 'To ensure compliance with regulations', 'To identify and prioritize risks', 'To train employees on safety protocols'],
          correctIndex: 2,
          hint: '',
          questionType: QuizQuestionType.text,
          level: levels[0]),
    ]
  )
];