// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhBD03VFrXdZoQ0sjeEihzt26NAbBye2w',
    appId: '1:992662012657:web:29e66af239eba04e1d9f50',
    messagingSenderId: '992662012657',
    projectId: 'hseassist-dd926',
    authDomain: 'hseassist-dd926.firebaseapp.com',
    storageBucket: 'hseassist-dd926.firebasestorage.app',
    measurementId: 'G-EJ2HH1QFFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfPMHsI88wOIFsDkjUNnchhUJ_R8CdEl0',
    appId: '1:992662012657:android:38695a5b66dcdc9c1d9f50',
    messagingSenderId: '992662012657',
    projectId: 'hseassist-dd926',
    storageBucket: 'hseassist-dd926.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsfNUsl2pvVIsTfRzuy0oI2Yan31VxzlE',
    appId: '1:992662012657:ios:49bbfde90d5e2c091d9f50',
    messagingSenderId: '992662012657',
    projectId: 'hseassist-dd926',
    storageBucket: 'hseassist-dd926.firebasestorage.app',
    androidClientId: '992662012657-ghl85mimpq20878spll6oa1mfls362cg.apps.googleusercontent.com',
    iosClientId: '992662012657-nqpfcgrdt6a2fb95grn00tn701qel0u8.apps.googleusercontent.com',
    iosBundleId: 'com.example.hseassist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsfNUsl2pvVIsTfRzuy0oI2Yan31VxzlE',
    appId: '1:992662012657:ios:49bbfde90d5e2c091d9f50',
    messagingSenderId: '992662012657',
    projectId: 'hseassist-dd926',
    storageBucket: 'hseassist-dd926.firebasestorage.app',
    androidClientId: '992662012657-ghl85mimpq20878spll6oa1mfls362cg.apps.googleusercontent.com',
    iosClientId: '992662012657-nqpfcgrdt6a2fb95grn00tn701qel0u8.apps.googleusercontent.com',
    iosBundleId: 'com.example.hseassist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwd_QJFWggBcbKEMjc9KULiAiL2h49h4U',
    appId: '1:992662012657:web:3f08fd945d3a0b221d9f50',
    messagingSenderId: '992662012657',
    projectId: 'hseassist-dd926',
    authDomain: 'hseassist-dd926.firebaseapp.com',
    storageBucket: 'hseassist-dd926.firebasestorage.app',
    measurementId: 'G-SLQHC26725',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: "AIzaSyDhBD03VFrXdZoQ0sjeEihzt26NAbBye2w",
    authDomain: "hseassist-dd926.firebaseapp.com",
    projectId: "hseassist-dd926",
    storageBucket: "hseassist-dd926.firebasestorage.app",
    messagingSenderId: "992662012657",
    appId: "1:992662012657:web:29e66af239eba04e1d9f50",
    measurementId: "G-EJ2HH1QFFG"
  );
}